### ISSUE TITLE
Is there any possible way to get this working for the Alien RPG?

### ISSUE THREAD

**Issue by NomadOfEndings** [Saibot393/LocknKey#137]
This mod would be PERFECT for my Alien's campaign (Keycards seem to be traded between left and right more then pokemon cards lol.) BUT your LocknKey mod doesn't seem to work with how the system is setup for Foundry. There might be a few issues where the character sheet inventory has 3 states for items to be in (Active, Inactive, or in your Foot Locker.) But also, when you create a key with your mod in the Alien Foundry System, the Lock and Key section under the item settings is black, with no options available that I saw with the Pathfinder and D&D tutorial videos.

If there is any way you could perform a miracle to get this working with the Alien RPG on Foundry, I'd be absolutely ecstatic! :)

**Comment by Saibot393** [comment]
I will look into it, should (probably) a relatively easy fix. I am not sure when i will have time for that though, as i am in the middle of making all my modules v13 compatible, so it might take a week or two

**Comment by NomadOfEndings** [comment]
The fact that you'll even look into it when you get around to it is more amazing/enough for me :)

**Comment by Saibot393** [comment]
I just released v4.0.3, the module should now be compatible (i only tested on v13, as that is the version i currently have installed, but it should also work for v12)

**Comment by NomadOfEndings** [comment]
I tried the newest version with v12 (can't update all my games yet since a lot of mods haven't been updated for v13.) But the Lock and Key menu is now showing up under the items BUT still no luck with unlocking any doors with keys that are made from that door. If it helps for bug hunting, the prompt "no matching key" isn't showing up when you right click with the door key in the inventory, but the prompts for "Can't break/lockpick door" are showing up.

I also tried enabling the password prompt for the door but nothing is showing up either. If more feedback or testing is needed, let me know what I can do to help. I'll also try v13 at some point when I get a chance to back up all my games before installing a fresh version of Foundry to tinker around with it.

**Comment by Saibot393** [comment]
I just tested it and everything seems to work as intended, regarding the keys. How exactly did you setup the key/which lock ids did you use?

**Comment by NomadOfEndings** [comment]
I was just using the normal "Shift + Right Click" on the locked door to create the key, then hand it off to the Character that would be attempting to open the door, no message appeared stating "No Matching Key" nor would the door unlock.

I also made sure to check the L&K ID of the Door and matched it with the created key's ID under the items own L&K tab. Like I said, this is testing under v12 of Foundry. I also disabled all the Mods except for Item Piles when testing as well, I'm still getting the same results. I'm not sure what I'm doing wrong, but I followed the instructions under those 2 tutorial videos that were listed with the mod.

When you were testing it, did it matter where the key was stored on the characters inventory, because I tried all 3 (Active, Inactive, Foot Locker) and nothing seems to be registering in any of those slots.

**Comment by Saibot393** [comment]
I did a new test under v12, everything still seems fine. For testing purposes, do you have the (Lock & Key) setting "Message popups" and the (core) setting "Scrolling status text" active? Those are required for the text popups.
I have the key item stored under "Inactive", though this is only the case because that was where the item was placed when i gave it to the actor and i haven't found an option to activate the item.
Are there any errors in the console (F12) when using the key?

**Comment by NomadOfEndings** [comment]
Message Pop Ups and Scrolling Status Text are checked. No Errors are popping up in the Console when I run it or attempt to open the lock (mind you the text prompts for "Can't Pick/Break" lock are still popping up as well as the text for "Door is locked" but right clicking doesn't give any prompt on the door when the character is holding the key to that door that have matching ID's. :(

**Comment by Saibot393** [comment]
Could you send mes creenshots of your doors Lock & Key and key configuration and the keys Lock & Key configuration?

**Comment by NomadOfEndings** [comment]
![Image](https://github.com/user-attachments/assets/8363fc46-e2b0-4f04-92cf-9fca7c8fb4cb)

![Image](https://github.com/user-attachments/assets/50b6eb41-3a45-476a-b233-f65da3615923)

**Comment by Saibot393** [comment]
Just in case something strange is happening with the inventory, could you select the token with the key,execute this command in the console, and send me the output?
`canvas.tokens.controlled[0].actor.items.find(i => i.flags.LocknKey?.IDKeysFlag
 == "lf3P82CFH2aM7iTB")`

**Comment by NomadOfEndings** [comment]
![Image](https://github.com/user-attachments/assets/a01d5466-107c-45c5-9c98-33b8e32d01ca)

**Comment by Saibot393** [comment]
Ok, that works. A few questions:
- How are you testing the keys, are you logged in as a GM or as a Player, in case you are logged in as a Player, are you also logged in as a GM?
- Did you change any of the Lock & Key settings, especially those related to items?
- Which browser are you using/are you using the Foundry client?

**Comment by NomadOfEndings** [comment]
- I set everything up as a GM, give that character a separate player owned account, then log out and switch to the player account to test it.

- None of the settings have been changed.

- Using the Foundry Client itself when testing as GM and Player.

**Comment by Saibot393** [comment]
I think the problem is, that you are only logged in as a player. Also being logged in as a GM while testing should fix the problem. The reason for that is, that Players can normally not change the state of doors, so for Lock & Key to work i needed to basically reroute the document change through a GM account.

**Comment by NomadOfEndings** [comment]
Ah, I'll keep you updated if it still doesn't work but I gotta wait till one of my players logs on to help me test this then.... If you don't hear back, then assume your advice worked :)
