### ISSUE TITLE
Popup menu new option now showing correct text

### ISSUE THREAD

**Issue by MastaGooz** [Saibot393/LocknKey#57]
Seems like the new options is not showing the correct text in the popup menu?

![image](https://github.com/Saibot393/LocknKey/assets/149971487/f36649e8-925a-4681-b66d-c3c2904d468a)

Also I could not get the new pickpocket feature to work, is it system dependant or is there a way to use it by using a shortcut?

**Comment by Saibot393** [comment]
I forgot to add the text replacement code for the custom check, i will quickly fix that. Regarding the pick pocketing: It can be triggered via the new "Pick pocket" key (no default value set) or the new macro (player folder) "Pick pocket". If it is active for a token (Pick pocket DC =/= -1) it should also be displayed in the action windows (the one in your screenshot).

**Comment by Saibot393** [comment]
I have added the missing translation with v2.0.1

**Comment by MastaGooz** [comment]
Here is the new FR translation : 
[fr.json](https://github.com/Saibot393/LocknKey/files/13322849/fr.json)

I noticed that when I use the pick pocket action on a character, I don't see anything in his inventory (i'm using Custom System Builder), maybe this functon is system dependant?

![image](https://github.com/Saibot393/LocknKey/assets/149971487/2e7a0993-899f-494a-ac84-b8be3e3fe96c)

**Comment by Saibot393** [comment]
Thanks for the translation update, much apreciated.

Custom system builder is indeed not supported currently, sorry. I will look into it immediately.

**Comment by MastaGooz** [comment]
Ok, thanks a lot !

**Comment by Saibot393** [comment]
I have just released v2.0.3, i have added Custom System Builder support based on the example system provided. In case this doesn't work, are you using one of the provided systems, if yes, which one? If not, is there somewhere where i can download the system you use/can you send me the system file (preferable with at least one example item)?
The update also includes your translation update, thanks again.

**Comment by MastaGooz** [comment]
No,  it's not working, I still can't see any item when I use pick pocket.
Do you want the "world" file or the "system" file? 

I'm using standard CSB that I got on foundry, but the system is empty (that's the point), so things like quantity have to be set up manually (using a key) inside the item. But the inventory (items carried by the character) is still kinda built-in I guess.
Idk if i'm answering your question correctly, I hope so.

**Comment by Saibot393** [comment]
I need the json you can download in the settingstab (middle) and the json you can download when right clicking an item. The world file should work too though.

**Comment by MastaGooz** [comment]
Oh ok :

[export.json](https://github.com/Saibot393/LocknKey/files/13323862/export.json)
World

[fvtt-Item-random-template-B9SuC3GSeVBhSN2y.json](https://github.com/Saibot393/LocknKey/files/13323864/fvtt-Item-random-template-B9SuC3GSeVBhSN2y.json)
Just a random item template with only one key (quantity)

[fvtt-Item-random-item-ji5xoVJNd8JcBcL2.json](https://github.com/Saibot393/LocknKey/files/13323867/fvtt-Item-random-item-ji5xoVJNd8JcBcL2.json)
A random item (the one on the character), based on the template

**Comment by Saibot393** [comment]
The newest v2.0.4 should now be compatible with the system (hopefully)

**Comment by MastaGooz** [comment]
This works but when I take something, if the remaining quantity is 0, then the item doesn't disappear from the character I stole. Is it possible to do something about it?

Nothing to do with this issue, but I was wondering if it would be possible in the future to steal money via the item pile currency system? That would be awesome.

**Comment by Saibot393** [comment]
That items remain with 0 stacks i currently intentional. There is a chance that some systems/modules may do something weird with that doesn't behave well with the item copy i use. So in case something weird happen, the original still remains in the source inventory. Deleting the items isn't a problem, i just want to wait a few weaks incase some bugs with item copying arise.

Adding currency should be possible. I will need an export of the character data sheet you use though to see what the currency path is.

**Comment by MastaGooz** [comment]
Ok nice ! This is a simple character with 3 main currencies and 3 secondary currencies (like it is possible to do with item pile).
[fvtt-Actor-niz-BuATNbUkOayPSTR2.json](https://github.com/Saibot393/LocknKey/files/13325238/fvtt-Actor-niz-BuATNbUkOayPSTR2.json)

**Comment by Saibot393** [comment]
I think currencies should now appear and be transfered correctly with v2.0.5

**Comment by MastaGooz** [comment]
This is working great, awesome man thanks !
Btw do you have any plateform where people can support your work?

**Comment by Saibot393** [comment]
Glad to hear that it works.
No, i don't have any platform for that.
